insert into Department (Name, Budget) values ('Business Development', 879001);
insert into Department (Name, Budget) values ('Product Management', 400398);
insert into Department (Name, Budget) values ('Accounting', 343365);
insert into Department (Name, Budget) values ('Engineering', 903182);
insert into Department (Name, Budget) values ('Marketing', 437488);
insert into Department (Name, Budget) values ('Accounting', 783918);
insert into Department (Name, Budget) values ('Legal', 216759);
insert into Department (Name, Budget) values ('Research and Development', 388679);
insert into Department (Name, Budget) values ('Services', 643015);
insert into Department (Name, Budget) values ('Business Development', 679928);
